# dependabot.yml 文件有两个必需的顶级key：version 和 updates。
version: 2
updates:
  # 启用npm的版本更新
  - package-ecosystem: 'npm'
    # 在根目录下寻找 `package.json` and `lock` 文件
    directory: '/'
    schedule:
      # 检查 `npm` 包更新的频率。daily: 每个工作日, weekly: 每周一, monthly: 每月一号
      interval: 'weekly'
    # Dependabot 最多打开版本更新请求数，默认 5
    open-pull-requests-limit: 20
